"""add_age_to_users

Revision ID: 030d53cf2692
Revises: 4a7e16a5fd82
Create Date: 2022-07-24 19:27:19.849645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030d53cf2692'
down_revision = '4a7e16a5fd82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.String(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
