"""add-phone-number

Revision ID: 4a7e16a5fd82
Revises: 841dc1fc8c76
Create Date: 2022-07-24 15:13:25.977172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7e16a5fd82'
down_revision = '841dc1fc8c76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'share')
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.add_column('posts', sa.Column('share', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
