"""create-posts-table

Revision ID: 977acf5468fb
Revises: 
Create Date: 2022-07-24 15:02:46.338498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977acf5468fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
